### ISSUE TITLE
Calling `compilemessages` management command from `setup.py` breaks `tox`.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-pages#74]
When trying to run `tox` on a project that is installing `django-fluent-pages` from git in `requirements.txt` (with `-e`), Django raises an exception when `compilemessages` is called because at that point, the project (and its settings module), of which `django-fluent-pages` is a dependency, has not yet been installed into the virtualenv.

This doesn't happen when installing normally (not via `tox`), perhaps because the current working directory is added to the `PYTHONPATH`?

Can that call be made optional somehow, or otherwise not raise an exception when it fails for this reason?

Alternatively, I'll have to install django-fluent-pages without `-e` which makes it more difficult to contribute any changes back.

**Comment by vdboor** [comment]
Ahh this is a good point. I didn't run into this yet because:
* I also have Django in the global path
* I typically use `add2virtualenv` to add paths, only recently found out that `pip instal -e /local/path` provides a similar and better way.

This is definitely a bug, and I'm all for catching the errors in a `setup.py develop` mode. As long as sdist will be unaffected, I'm happy! :)

**Comment by vdboor** [comment]
Fixed in 215cdb659d1d8d3e78ffb01f9a2718b96ba9db78
